"""Remove superuser

Revision ID: 07b6daf36c8d
Revises: 589c785f6608
Create Date: 2024-12-12 18:11:48.928737

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07b6daf36c8d'
down_revision: Union[str, None] = '589c785f6608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circuit', 'trace',
               existing_type=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               comment='A LINESTRING built from the GPS measured track, in WGS 84 lat/long (4326)',
               existing_nullable=False)
    op.alter_column('strava_link', 'expires_at',
               existing_type=mysql.INTEGER(),
               comment='in seconds, from the UNIX epoch',
               existing_nullable=False)
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.alter_column('strava_link', 'expires_at',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='in seconds, from the UNIX epoch',
               existing_nullable=False)
    op.alter_column('circuit', 'trace',
               existing_type=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               comment=None,
               existing_comment='A LINESTRING built from the GPS measured track, in WGS 84 lat/long (4326)',
               existing_nullable=False)
    # ### end Alembic commands ###
