"""Update activation table

Revision ID: 0e6aff58e332
Revises: 5176c5d8830a
Create Date: 2024-11-23 22:50:31.377171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0e6aff58e332'
down_revision: Union[str, None] = '5176c5d8830a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('user', 'gender',
               existing_type=mysql.INTEGER(),
               type_=sa.Enum('male', 'female', name='genderenum'),
               existing_nullable=True)
    op.drop_index('ix_user_username', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.alter_column('user', 'gender',
               existing_type=sa.Enum('male', 'female', name='genderenum'),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
