"""Add activation table

Revision ID: 5176c5d8830a
Revises: 91211d6cd2b8
Create Date: 2024-11-23 17:24:25.418933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5176c5d8830a'
down_revision: Union[str, None] = '91211d6cd2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activation')
    # ### end Alembic commands ###
